### ISSUE TITLE
appium-doctor Error report in execution    如何解决 How to solve this problem

### ISSUE THREAD

**Issue by DObett** [appium/appium-doctor#105]
C:\Users\Administrator>appium-doctor

C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\_bluebird@3.7.2@bluebird\js\release\promisify.js:270
        throw new TypeError("expecting a function but got " + util.classString(fn));
              ^
TypeError: expecting a function but got [object Undefined]
    at Function.promisify (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\_bluebird@3.7.2@bluebird\js\release\promisify.js:270:15)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\_appium-support@2.48.1@appium-support\lib\zip.js:17:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\_appium-support@2.48.1@appium-support\index.js:10:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

**Comment by KazuCocoa** [comment]
What version of node did you use to install it?

**Comment by DObett** [comment]
> 您使用哪个版本的节点进行安装？



> What version of node did you use to install it?

thank you     It's settled    

Node version 6.0 has been updated 14.    3Q
