### ISSUE TITLE
Error after upgrading to MacOS High Sierra 

### ISSUE THREAD

**Issue by alcamla** [appium/appium-doctor#29]
When running Appium doctor, in MacOS High Sierra I am getting the following error:

`Could not detect Mac OS X Version from sw_vers output: '10.13'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/build/lib/system.js:114:15)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by ikhilko** [comment]
Looks like need to up version of https://github.com/appium/appium-support in deps to "2.10.0"

**Comment by imurchie** [comment]
Just reinstall the `appum-doctor` package. The dependencies should upgrade to the latest and work.
