### ISSUE TITLE
Can't open appium doctor (node version: v8.16.2, macOS: Catalina)

### ISSUE THREAD

**Issue by andree007** [appium/appium-doctor#85]
Can you please help with this error: 

/Users/andreecarreno/.nvm/versions/node/v8.16.2/lib/node_modules/appium-doctor/build/lib/general.js:59
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andreecarreno/.nvm/versions/node/v8.16.2/lib/node_modules/appium-doctor/lib/factory.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andreecarreno/.nvm/versions/node/v8.16.2/lib/node_modules/appium-doctor/bin/appium-doctor.js:4:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**(node version: v8.16.2, macOS: Catalina)**

**Comment by imurchie** [comment]
Appium supports Node 10+.

**Comment by andree007** [comment]
> Appium supports Node 10+.

thank you sir

**Comment by imurchie** [comment]
You're welcome!
